name: Deploy to OVH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Upload to OVH
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        sudo apt-get install -y lftp
        lftp -e "
          open $FTP_SERVER
          user $FTP_USERNAME $FTP_PASSWORD
          mirror --reverse --delete --verbose --exclude .git/ dist/ /www/
          bye
        "