name: Deploy to OVH

on:
  push:
    branches:
      - main  # Remplacez par la branche que vous souhaitez déployer

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Upload to OVH
      env:
        FTP_SERVER: ${{ secrets.FTP_SERVER }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        # Installer lftp pour le transfert FTP
        sudo apt-get install -y lftp
        # Transférer les fichiers vers le serveur OVH
        lftp -e "
          open $FTP_SERVER
          user $FTP_USERNAME $FTP_PASSWORD
          mirror --reverse --delete --verbose --exclude .git/ . /www/
        "